### DISCUSSION TITLE
Equalizer (EQ) Profile for Onju Voice (Music Assistant >=v2.4)

### DISCUSSION THREAD

**Discussion by rmeissn** [tetele/onju-voice-satellite#113] [General]
I'm using Onju Voice (with a tuned ESPHome media player, see https://github.com/tetele/onju-voice-satellite/pull/77) as an Alexa replacement for my child. The original Google board had significantly better sound quality than the Onju board - music quality dropped noticeably, as discussed in https://github.com/tetele/onju-voice-satellite/issues/52#issuecomment-2453506994 and https://github.com/tetele/onju-voice-satellite/discussions/100#discussion-7673704

With the recent release of Music Assistant v2.4, it's now possible to post-process the music stream using a DSP, offering either a simple three-band EQ (bass, mids, treble) or a more advanced multi-band EQ.

What EQ settings have you found effective for improving the Onju's sound using Music Assistant's DSP?

My initial attempt with the simple three-band EQ already made a noticeable difference, even though I'm not proficient in calibrating EQs:
Bass: +5db
Mids: -4db
Treble: +5db

EDIT: This won't improve how home assistant assist responses sound like, but at least music will sound much better.

**Comment by tetele** [comment]
It still sounds bad with 48kHz? I don't expect it to sound as good as the original board (no idea what sampling rate and bitrate that used), but still 48kHz should be decent.

The only issue is that the microphone needs to be at 16kHz for the voice stuff to work, and you can't have different sampling rates for the mic/speaker since they're on the same hardware I2S bus.

**Reply by rmeissn** [reply]
I think music quality (khz and bits/s) at 48kHz is generally fine. However, I suspect Google calibrated their original board against a reference device, creating an EQ profile that was applied to it but is missing on the Onju. As a result, there's not enough bass and too much midrange, making it sound tinny, almost like a canister, without an EQ.

About 16 vs 48khz:
This is a stripped-down configuration (showing only the relevant parts) that illustrates how audio components are set up at my site. Based on my understanding and the speaker settings in Music Assistant, MA streams audio at either 44.1kHz/16-bit or 48kHz/16-bit to the Onju, which resamples it to 48kHz before passing it to the I2S subsystem, configured for 48kHz. On the input side, the microphone receives a 48kHz signal from I2S, which is then resampled (though I’m unsure of the exact settings) to match the input requirements of the voice assistant.

This configuration works well for both music playback and voice commands, including wake word detection through MWW. ... Unfortunately, wake word detection sometimes fails - Onju stops responding to the wake word until restarted. However, I suspect this issue is unrelated to the I2S pipeline settings and may instead be due to an unstable MWW execution or some other exception raising.

See this config for a full example: https://github.com/dreimer1986/onju-voice-satellite/blob/main/esphome/onju-voice-microwakeword.yaml

```
external_components:
  - source:
      type: git
      url: https://github.com/gnumpi/esphome_audio
      ref: dev-next
    components: [adf_pipeline, i2s_audio]

i2s_audio:
  - id: i2s_shared
    i2s_lrclk_pin: GPIO13
    i2s_bclk_pin: GPIO18
    access_mode: duplex

adf_pipeline:
  - platform: i2s_audio
    type: audio_out
    id: adf_i2s_out
    i2s_audio_id: i2s_shared
    i2s_dout_pin: GPIO12
    fixed_settings: true
    channel: left
    alc_max: 0.5
    use_apll: true
    bits_per_sample: 32bit
    adf_alc: true
    sample_rate: 48000

  - platform: i2s_audio
    type: audio_in
    id: adf_i2s_in
    i2s_audio_id: i2s_shared
    i2s_din_pin: GPIO17
    fixed_settings: true
    channel: left
    pdm: false
    bits_per_sample: 32bit
    use_apll: true
    sample_rate: 48000

microphone:
  - platform: adf_pipeline
    id: onju_microphone
    keep_pipeline_alive: true
    gain_log2: 3
    pipeline:
      - adf_i2s_in
      - resampler
      - self

media_player:
  - platform: adf_pipeline
    id: onju_out
    icon: mdi:assistant
    name: None
    internal: false
    keep_pipeline_alive: true
    pipeline:
      - self
      - resampler
      - adf_i2s_out
    on_state:
      then:
        - lambda: |-
            static float old_volume = -1;
            float new_volume = id(onju_out).volume;
            if(abs(new_volume-old_volume) > 0.0001) {
              if(old_volume != -1) {
                id(show_volume)->execute();
              }
            }
            old_volume = new_volume;
            id(volume_percent) = old_volume;

voice_assistant:
  id: va
  microphone: onju_microphone
  media_player: onju_out
  use_wake_word: false
  noise_suppression_level: 2
  ...


```
