### DISCUSSION TITLE
Upside down OnjuVoice

### DISCUSSION THREAD

**Discussion by andrew-codechimp** [tetele/onju-voice-satellite#43] [Show and tell]
I have an OnjuVoice on a stand where the power cable comes out the bottom, which means the led's and buttons are reversed.

Not wanting to deviate too much from the published version I used substitutions and the partitions reversed flag to quickly flip around that device at compile time.

```
substitutions:
  volume_down_pin: "GPIO2"
  volume_up_pin: "GPIO4"
  volume_reversed: "True"
  volume_right_led: "0"
  volume_left_led: "5"
...
  - platform: esp32_touch
    id: volume_down
    pin: ${volume_down_pin}
...    
  - platform: esp32_touch
    id: volume_up
    pin: ${volume_up_pin}
...
  - platform: partition
    id: left_led
    segments:
      - id: leds
        from: ${volume_left_led}
        to: ${volume_left_led}
    default_transition_length: 100ms
  - platform: partition
    id: top_led
    segments:
      - id: leds
        from: 1
        to: 4
        reversed: ${volume_reversed}
    default_transition_length: 100ms
...
  - platform: partition
    id: right_led
    segments:
      - id: leds
        from: ${volume_right_led}
        to: ${volume_right_led}
    default_transition_length: 100ms

```
