### DISCUSSION TITLE
How to use more than one sound to wakeup

### DISCUSSION THREAD

**Discussion by witold-gren** [tetele/onju-voice-satellite#87] [Show and tell]
If you need use more then one sound after you device will wakeup you can just replace one line.
From:
```
- media_player.play_media: "${wakeup_sound_url}"
```
To:
```
- media_player.play_media: !lambda 'const char* sounds[] = {"http://media-url/media1.mp3","http://media-url/media2.mp3","http://media-url/media3.mp3","http://media-url/media4.mp3"}; int random_index = random() % 4; return sounds[random_index];'
```

The all section should look like below:
```
micro_wake_word:
  models:
    #- model: https://github.com/kahrendt/microWakeWord/releases/download/v2.1_models/alexa.json
    # - model: https://github.com/kahrendt/microWakeWord/releases/download/v2.1_models/okay_nabu.json
    - model: https://github.com/kahrendt/microWakeWord/releases/download/v2.1_models/hey_jarvis.json
    #- model: https://github.com/kahrendt/microWakeWord/releases/download/v2.1_models/hey_mycroft.json
  vad:
    model: https://github.com/kahrendt/microWakeWord/releases/download/v2.1_models/vad.json
  on_wake_word_detected:
    - if:
        condition: media_player.is_playing
        then:
          - media_player.pause
    - media_player.play_media: !lambda 'const char* sounds[] = {"http://media-url/media1.mp3","http://media-url/media2.mp3","http://media-url/media3.mp3","http://media-url/media4.mp3"}; int random_index = random() % 4; return sounds[random_index];'
    - wait_until:
        not:
          media_player.is_playing: onju_out
    - voice_assistant.start:
        wake_word: !lambda return wake_word;
```
