### DISCUSSION TITLE
How to add extra switch to to start conversation with the assist

### DISCUSSION THREAD

**Discussion by witold-gren** [tetele/onju-voice-satellite#88] [Show and tell]
If you need add extra button which you will just click to start conversation with the assist without use wake work just copy yaml configuration below and add it to `switch` configuration:
```
switch:
  ...
  - platform: template
    name: Listen Once    
    id: listen_once
    optimistic: true
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - switch.turn_off: use_wake_word
      - delay: 0.5s
      - voice_assistant.start
    on_turn_off:
      - switch.turn_on: use_wake_word  
```

after that you will see extra button which you can you in your automation. 
<img width="335" alt="image" src="https://github.com/user-attachments/assets/17ef92bf-a043-4e51-8595-4131f867747e">

BTW. Before you start using `start_va` esphome script you must always disable `use_wake_word`. This button solve this problem because the do automatically for you 😀 

This configuration will not turn off switch when voice_assistant will finish pipeline. If it is important to you to auto disable this switch and enable wake_words then you must add one extra line `switch.turn_off: listen_once` to `voice_assistant` configuration:
```
voice_assistant:
  ...
  on_end:
    - wait_until:
        not:
          media_player.is_playing:
    - script.execute: reset_led
    - switch.turn_off: listen_once    # <----- add this line here
    - if:
        condition:
          and:
            - switch.is_on: use_wake_word
            - binary_sensor.is_off: mute_switch
        then:
          - micro_wake_word.start
```

**Comment by TheStigh** [comment]
Hi @witold-gren Question: Do you use the improved audio part (adf_pipline) or the arduino framework?

**Reply by witold-gren** [reply]
I use `adf_pipeline`. All this changes is necessary for provide continue conversation in Onju Voice.. I have an Idea how to run it on all device using one automation. I also have an idea how to create automation with queries to which we answer e.g. `Yes` or `Do it`. and Home Assistant (Automation) will know what to do.. the only problem I have is the inability to interrupt the pipeline directly in ESP. If I manage to get it working, I will definitely share the solution..

**Reply by TheStigh** [reply]
I've already built;
- One firmware, where you select On device or Home Assistant for wakeword
- Can use a sentence to open a conversation, and a different sentence to finish the conversation (Automation)
- Random custom 'welcome messages' after saying the wakeword
- ADF Pipeline
- Transcripts of STT and TTS in HA

We should hookup with a chat somewhere :)

**Reply by witold-gren** [reply]
yep.. it will be nice 😀 Can you share somewhere your solution? I won't have to invent something that already exists 😁

**Reply by TheStigh** [reply]
I guess you're at the HA community? Look me up (TheStigh) and pop me a message, there we can hook up on Telegram or WhatsApp. I do not want to share those details here "for the world", neither do you I imagine :)

**Reply by witold-gren** [reply]
BTW. This is my problem. I created extra switch in ESP:
```
switch:
  ...
  - platform: template
    name: Disable processing response
    id: disable_processing_response
    optimistic: true
    restore_mode: ALWAYS_OFF
```
And then I add some automation to ESP:
```
voice_assistant:
  ...
  on_stt_end:
    - text_sensor.template.publish:
        id: text_request
        state: !lambda return x;
    - if:
        condition:
          and:
            - switch.is_on: disable_processing_response
            - voice_assistant.is_running
        then:
          - HOW TO STOP PROCESSING PIPELINE THERE???
```
And I don't know how to stop processing pipeline after I save in other sensor "request" for Onju Voice 😀 I only need question because this question will be use like a "response" in my HA automation 😉 Do you have any idea how to do it?

**Reply by witold-gren** [reply]
yep, I'm in HA community.. do you use Discord?

**Reply by TheStigh** [reply]
Sorry, I do not use Discord.

Regarding the THEN: It is a timing issue I think actually is related to using the ADF_Pipeline. For testing purposes, just try to add a delay and check the outcome, like I did here:

```
        condition:
          and:
            - switch.is_off: use_wake_word
            - switch.is_on: listen_conversation
        then:
          - switch.turn_off: listen_conversation
          - delay: 2s
          - switch.turn_on: listen_conversation
``` 

This weekend I will spend more time digging into the pipeline so I do not use the delay but really follow the state to stop the conversation at the right time. By this I mean, I could stop it without the delay but it didn't return til active listening for wakeword.
