### DISCUSSION TITLE
How to save last text request and last text response from this device

### DISCUSSION THREAD

**Discussion by witold-gren** [tetele/onju-voice-satellite#89] [Show and tell]
If you need save last text request and last text response, first of all you must create two extra entity. Just copy and paste below code before `binary_sensor`:
```
text_sensor:
  - platform: template
    id: text_request
    name: "Text request"
    icon: "mdi:microphone"
  - platform: template
    id: text_response
    name: "Text response"
    icon: "mdi:volume-high"

binary_sensor:
  ...
```

If you need filter to not save all sentence you can use some lambda function to cut part of sentences..
```
text_sensor:
  - platform: template
    id: text_request
    name: "Text request"
    icon: "mdi:microphone"
    on_value:
      lambda: |-
        if(id(text_request).state.length()>32) {
          std::string name = id(text_request).state.c_str();
          std::string truncated = esphome::str_truncate(name.c_str(),31);
          id(text_request).state = (truncated+"...").c_str();
        }
  - platform: template
    id: text_response
    name: "Text response"
    icon: "mdi:volume-high"
    on_value:
      lambda: |-
        if(id(text_response).state.length()>32) {
          std::string name = id(text_response).state.c_str();
          std::string truncated = esphome::str_truncate(name.c_str(),31);
          id(text_response).state = (truncated+"...").c_str();
        }

binary_sensor:
  ...
```

The you must add two extra extra two function to `voice_assistant` configuration:
```
voice_assistant:
  ...
  on_stt_end:
    - text_sensor.template.publish:
        id: text_request
        state: !lambda return x;
  on_tts_start:
    - text_sensor.template.publish:
        id: text_response
        state: !lambda return x;
```

Now you should see result directly on device 😀 

<img width="332" alt="image" src="https://github.com/user-attachments/assets/646feca6-9dd9-4779-a596-7d8dcf693d14">
