### DISCUSSION TITLE
How to provide Continued conversation without wake word but still support normal one time shot sentences?

### DISCUSSION THREAD

**Discussion by witold-gren** [tetele/onju-voice-satellite#90] [Show and tell]
At the beginning you need update your Onju Voice device and you need create extra switch.
1. Create two extra switch in the bottom of the file:
```
switch:
  ...
  - platform: template
    name: Continued conversation
    id: continued_conversation
    optimistic: true
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - if:
          condition:
            - switch.is_off: listen_once
          then:
            - switch.turn_on: listen_once
    on_turn_off:
      - switch.turn_on: use_wake_word
  - platform: template
    name: Listen Once
    id: listen_once
    optimistic: true
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - switch.turn_off: use_wake_word
      - delay: 0.5s
      - voice_assistant.start
    on_turn_off:
      - switch.turn_on: use_wake_word
```
2. Update your `voice_assistant` pipeline:
```
voice_assistant:
  ...
  on_tts_start:
    - switch.turn_off: listen_once
```
The last part is update your `media_player` configuration and add state `on_idle`:
```
media_player:
  ...
  - platform: adf_pipeline
    ...
    on_idle:
      - if:
          condition:
            - switch.is_on: continued_conversation
          then:
            - delay: 2s
            - switch.turn_on: listen_once
```
That's all you need to prepare in the Onju Voice configuration itself. We create two buttons:
1. One button (continued_conversation) that will inform our device that we want to engage in continuous conversation.
2. The second button (listen_once) that will make it easier to wake up the assistant without using wake words. This button can also be used in automations to wake up the microphone to download some content from it without using wake words.

The second step is to prepare simple automation:
```
alias: Continued Conversation
description: "Very simple automation allowing for continuous conversation"
mode: single
trigger:
  - platform: conversation
    command:
      - can we talk
      - talk
    id: start_conversation
  - platform: conversation
    command:
      - finish
      - the end
    id: finish_conversation
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - start_conversation
        sequence:
          - set_conversation_response: Of course, lets talk. What do you want to talk about?
          - action: switch.turn_on
            data_template:
              entity_id: >-
                {{ device_entities(trigger.device_id) | select('contains', 'continued_conversation') | list }}
      - conditions:
          - condition: trigger
            id:
              - finish_conversation
        sequence:
          - set_conversation_response: Thank you for the nice conversation, have a good day!
          - action: switch.turn_off
            target:
              entity_id: >-
                {{ device_entities(trigger.device_id) | select('contains', 'continued_conversation') | list }}
```
Of course, you can expand this simple automation a lot (as in my case of the Polish language), but its main assumption is to turn on and off one button on the device that started the conversation with you.

That's all. 😀 If you turn on the button `continued_conversation` in this automation or manually in device dashboard you will be able to talk without interruption until this button is turned off. This solution is not the fastest (the device needs 2-3 seconds to reaction) as I discovered a few problems... but for now I won't share it here until I understand exactly how the various ESPHome components work.
