### DISCUSSION TITLE
MicroWakeWord version reboots on every second voice command

### DISCUSSION THREAD

**Discussion by rmeissn** [tetele/onju-voice-satellite#98] [Q&A]
### Flavor

MicroWakeWord

### Checklist

- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/tetele/onju-voice-satellite/issues?q=is%3Aissue+label%3A%22bug%22+)..
- [X] I am able to consult debug logging for my ESPHome instance.

### Describe the issue

While I'm not using an Onju Board - sorry for posting here - I've replicated the basic the setup (ESP32-S3 DevKitC-1 N16R8, Max9857 amp, an INMP441 Mic) and copied over a stripped down version of the code from this repository (stripping buttons, timers, led strip), while only adapting some pins to match my wiring for the amp and mic.

The setup works very good, except for asking the voice assistant something the second time. Whenever I'm asking something for the second time, the device seems to reboot on playing the answer. Did any of you encounter something similar?

My problem sounds similar to https://github.com/tetele/onju-voice-satellite/issues/24 , but there is no solution in this thread.

I'm using the MicroWakeWord Edition.

Maybe someone can give me an advice or point me onto something for how to proceed...

### Reproduction steps

1. Boot the device
2. Ask something ("Okay Nabu" -> Question -> Processing -> Answer is played correctly -> RGB Led indicates readiness)
3. Ask something ("Okay Nabu" -> Question -> Processing -> Board reboot as it receives the answer.)

### Code

I've played a bit with this configuration (see comments), but it should largly resemble the onju configuration for the mww version. I've tested both, the version from https://github.com/tetele/onju-voice-satellite/pull/77 and the original implementation of the ADF pipelines.
```
substitutions:
  name: "diy-voice-assistant"
  friendly_name: "DIY Voice Assistant"
  device_description: "Do It Yourself Voice Satellite with ESPHome software and microWakeWord"
  wakeup_sound_url: "http://192.168.0.202:8123/local/wakeup.mp3" # New Notification #7 by UNIVERSFIELD https://freesound.org/people/UNIVERSFIELD/sounds/736267/
  error_sound_url: "http://192.168.0.202:8123/local/error.mp3" # Error #8 by UNIVERSFIELD https://freesound.org/people/UNIVERSFIELD/sounds/734442/
  timer_finished_sound_url: "http://192.168.0.202:8123/local/timer_finished.mp3" # New Notification #6 by UNIVERSFIELD https://freesound.org/people/UNIVERSFIELD/sounds/734445/
  vad_model: "https://raw.githubusercontent.com/esphome/micro-wake-word-models/refs/heads/main/models/v2/vad.json"
  wakeword_model: "https://raw.githubusercontent.com/esphome/micro-wake-word-models/refs/heads/main/models/v2/okay_nabu.json"

external_components:
  - source:
      type: git
      url: https://github.com/gnumpi/esphome_audio
      ref: dev-next
    components: [adf_pipeline, i2s_audio]

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: "${device_description}"
  name_add_mac_suffix: true
  min_version: 2024.9.0
  platformio_options:
    board_build.flash_mode: dio
    #board_build.arduino.memory_type: qio_opi
  on_boot: 
    then:
      - light.turn_on:
          id: rgb_led
          effect: slow_pulse
          red: 100%
          green: 0%
          blue: 0%
      - media_player.volume_set: 70%
      - wait_until:
          condition:
            wifi.connected:
      - light.turn_on:
          id: rgb_led
          effect: pulse
          red: 0%
          green: 100%
          blue: 0%
      - wait_until:
          condition:
            api.connected:
      - light.turn_on:
          id: rgb_led
          effect: none
          red: 0%
          green: 100%
          blue: 0%
      - delay: 5s
      - light.turn_off: rgb_led

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB  
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32_S3_BOX_BOARD: "y"
     # I've found the following options in other repositories, but none of these seem to make a difference
      #CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      #CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      #CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      #CONFIG_AUDIO_BOARD_CUSTOM: "y"
      #CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM: "16"
      #CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM: "512"
      #CONFIG_TCPIP_RECVMBOX_SIZE: "512"
      #CONFIG_TCP_SND_BUF_DEFAULT: "65535"
      #CONFIG_TCP_WND_DEFAULT: "512000"
      #CONFIG_TCP_RECVMBOX_SIZE: "512"
  
psram:
  mode: octal
  speed: 80MHz

logger:

ota:
  platform: esphome

wifi:
  ssid: ...
  password: ...
  output_power: 8.5dB
  power_save_mode: none
  fast_connect: true
  manual_ip:
    static_ip: 192.168.0.203
    gateway: 192.168.0.1
    subnet: 255.255.255.0

improv_serial:

api:
  services:
    - service: start_va
      then:
        - voice_assistant.start
    - service: stop_va
      then:
        - voice_assistant.stop

i2s_audio:
  - id: i2s_in
    i2s_lrclk_pin: GPIO8
    i2s_bclk_pin: GPIO9
  - id: i2s_out
    i2s_lrclk_pin: GPIO15
    i2s_bclk_pin: GPIO16
# I've also tested the duplex mode, but it also resulty in reboots

adf_pipeline:
  - platform: i2s_audio
    type: audio_out
    id: adf_i2s_out
    i2s_audio_id: i2s_out
    i2s_dout_pin: GPIO17
    sample_rate: 48000
    alc_max: .5
    use_apll: true
    fixed_settings: true
    channel: left
    #sample_rate: 16000
    #adf_alc: true
    #alc_max: .5
    #bits_per_sample: 32bit
    #fixed_settings: true
    #channel: left
  - platform: i2s_audio
    type: audio_in
    id: adf_i2s_in
    i2s_audio_id: i2s_in
    i2s_din_pin: GPIO10
    channel: left
    pdm: false
    use_apll: true
    sample_rate: 48000
    fixed_settings: true
    #channel: left
    #pdm: false
    #sample_rate: 16000
    #bits_per_sample: 32bit
    #fixed_settings: true
    
microphone:
  - platform: adf_pipeline
    id: mic
    keep_pipeline_alive: true
    gain_log2: 3
    pipeline:
      - adf_i2s_in
      - resampler
      - self

media_player:
  - platform: adf_pipeline
    id: media_out
    name: Media Player
    internal: false
    keep_pipeline_alive: true
    pipeline:
      - self
      - resampler
      - adf_i2s_out

micro_wake_word:
  models:
    - model: "${wakeword_model}"
  vad:
    model: "${vad_model}"
  on_wake_word_detected:
    - if:
        condition: media_player.is_playing
        then:
          - media_player.pause
    - media_player.play_media: "${wakeup_sound_url}"
    - wait_until:
        not:
          media_player.is_playing: media_out
    - voice_assistant.start:
        wake_word: !lambda return wake_word;

voice_assistant:
  id: va
  microphone: mic
  media_player: media_out
  use_wake_word: false
  on_listening:
    - light.turn_on:
        id: rgb_led
        blue: 100%
        red: 100%
        green: 100%
        brightness: 100%
        effect: listening
  on_stt_vad_end:
    - light.turn_on:
        id: rgb_led
        blue: 100%
        red: 0%
        green: 20%
        brightness: 70%
        effect: processing
  on_tts_end:
    - light.turn_on:
        id: rgb_led
        blue: 0%
        red: 20%
        green: 100%
        effect: speaking
  on_end:
    - wait_until:
        media_player.is_idle
    - light.turn_off: rgb_led
    - delay: 100ms
    - if:
        condition:
          - switch.is_on: use_wake_word
        then:
          - micro_wake_word.start
  on_client_connected:
    - if:
        condition:
          - switch.is_on: use_wake_word
        then:
          - micro_wake_word.start:
  on_client_disconnected:
    - if:
        condition:
          - switch.is_on: use_wake_word
        then:
          - voice_assistant.stop:
          - micro_wake_word.stop:
  on_error:
    - media_player.play_media: "${error_sound_url}"
    - light.turn_on:
        id: rgb_led
        blue: 0%
        red: 100%
        green: 0%
        effect: none
    - delay: 1s
    - light.turn_off: rgb_led

# This is the onboard RGB LED
light:
  - platform: esp32_rmt_led_strip
    name: "RGB LED"
    id: rgb_led
    rgb_order: GRB
    pin: GPIO48
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    default_transition_length: 100ms
    effects:
      - pulse:
          name: pulse
          transition_length: 250ms
          update_interval: 250ms
      - pulse:
          name: slow_pulse
          transition_length: 1s
          update_interval: 2s
      - addressable_twinkle:
          name: listening_ww
          twinkle_probability: 1%
      - addressable_twinkle:
          name: listening
          twinkle_probability: 45%
      - addressable_scan:
          name: processing
          move_interval: 80ms
      - addressable_flicker:
          name: speaking
          intensity: 35%

script:
  - id: turn_on_wake_word
    then:
      - if:
          condition:
            - switch.is_on: use_wake_word
          then:
            - micro_wake_word.start
            - light.turn_off: rgb_led

  - id: turn_off_wake_word
    then:
      - micro_wake_word.stop
      - light.turn_off: rgb_led

switch:
  - platform: template
    name: Use Wake Word
    id: use_wake_word
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on:
      - script.execute: turn_on_wake_word
    on_turn_off:
      - script.execute: turn_off_wake_word
  - platform: template
    name: Wake Word Listening Light
    id: flicker_wake_word
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on:
      - light.turn_off: rgb_led
    on_turn_off:
      - light.turn_off: rgb_led
```
