### ISSUE TITLE
function 'on_end' does not perform as scripted, doesn't wait for media_player to finish

### ISSUE THREAD

**Issue by TheStigh** [tetele/onju-voice-satellite#84]
### Flavor

OpenWakeWord or no wake word

### Checklist

- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/tetele/onju-voice-satellite/issues?q=is%3Aissue+label%3A%22bug%22+)..
- [X] I am able to consult debug logging for my ESPHome instance.

### Describe the issue

Using openWakeWord (but tested now also using latest micrWakeWord version) and the device itself works fine with replies.

But the led's for process `on_tts_end` blink Blue for half a second.
As far as I can see, the function `media_player.is_playing: onju_out` is not "holding" until voice is finished. The device run's `on_end` about the same time as I hear the voice from the speaker.

Is this something that can be resolved?

```
  on_tts_end:
    - media_player.play_media: !lambda return x;
    - light.turn_on:
        id: top_led
        blue: 0%
        red: 20%
        green: 100%
        effect: speaking

  on_end:
    - delay: 100ms
    - wait_until:
        not:
          media_player.is_playing: onju_out

    - script.execute: reset_led
```

### Reproduction steps

1. Watch the logs and watch the LED when the mp3 file (response) is played.

...
